### ISSUE TITLE
Better 'kamu --help' message

### ISSUE THREAD

**Issue by LinuxUser404** [kamu-data/kamu-cli#4]
'kamu --help' is not the full help. There are help options for subcommands too. A user might not know he can run 'kamu pull -h' to get help on the pull subcommand.

**Comment by sergiimk** [comment]
When you do `kamu -h` at the bottom it currently writes:
```
To see help of individual subcommands use: kamu [COMMAND] -h
```

I intentionally disabled full help on sub-commands because it was very verbose and intimidating to see as a first help message for a new user.

Can you give full help a try and tell me what you think? It can be enabled by commenting out [this line](https://github.com/kamu-data/kamu-cli/blob/master/src/main/scala/dev/kamu/cli/CliParser.scala#L135).
