### ISSUE TITLE
`Thrift Server did not start: TimeoutError` error when launching SQL shell

### ISSUE THREAD

**Issue by ihainan** [kamu-data/kamu-cli#62]
And the error changed when I re-executed the same command:

```
(base) ➜  my-repo kamu sql
⠂ Starting Spark SQL shell
thread 'main' panicked at 'Thrift Server did not start: TimeoutError { duration: 60s, backtrace: <disabled> }', kamu-core/src/infra/explore/sql_shell_impl.rs:143:14
(base) ➜  my-repo kamu sql
⠚ Starting Spark SQL shell
thread 'main' panicked at 'Thrift server start script returned non-zero code: ExitStatusError(ExitStatusError(256))', kamu-core/src/infra/explore/sql_shell_impl.rs:130:18
```

Is there a way to restart the Thrift server and check the detailed log message?

**Comment by sergiimk** [comment]
The project have advanced significantly since this issue was open, so I'll close it.

If you want to try out the tool - you can use our [online demo](https://docs.kamu.dev/cli/get-started/self-serve-demo/) without needing to install anything. And if you still experiencing this issue when installing locally - please reopen this ticket and we'll investigate!

Cheers
