### ISSUE TITLE
Add validation for dataset existence in Fs mode

### ISSUE THREAD

**Issue by rmn-boiko** [kamu-data/kamu-cli#846]
### Describe the bug

It is possible to push dataset via transfer protocol with the same Id, but with different names in workspace with LocalFs dataset storage,

### Steps To Reproduce

I just created a new dataset in my local workspace.
- `kamu login http://localhost:1234`
- `kamu push gps --to "odf+http://localhost:1234/gps"`
- `kamu push gps --to "odf+http://localhost:1234/gps1"`

### Current Behavior

For both pushes, I will get a successful result

### Expected Behavior

User should get an error(similar to error when we try to push dataset to workspace with s3 dataset storage)

### kamu system info

```sh
-
```

**Comment by sergiimk** [comment]
This is closely related to #342 where we aim to change the FS layout to store datasets by ID instead of names.

If this issue can be addressed with a small patch - then we can do it before layout unification of course and that would be beneficial to prevent situation that definitely won't be allowed after unification.
